### ISSUE TITLE
incorrect lighting close to structure decorations

### ISSUE THREAD

**Issue by MekhailS** [sqrtyyy/VampGame#133]
![image.png](https://images.zenhubusercontent.com/601a6f01e91f91893f567dff/6ae3be5c-555c-4a97-91da-1e5d63caa1a1)
![image.png](https://images.zenhubusercontent.com/601a6f01e91f91893f567dff/05ba18ba-ba5a-48f2-9ca6-84367ea2f18a)
Если встать вплотную к структурным декорациям (колоннам, аркам), то свет освещает только эту декорацию.
(Мб теневые границы сделать в префабах структурных декораций?)

**Comment by ViktorOneLove** [comment]
Пытался решить данную проблему, безуспешно
