### ISSUE TITLE
Logic of the interaction of characters and tasks

### ISSUE THREAD

**Issue by ViktorOneLove** [sqrtyyy/VampGame#48]

**Comment by sqrtyyy** [comment]
Задание - это префаб у которого есть компонент ITask и Layer - Task
У персонажа есть точка и компонент ITaskCompleter
Задается радиус, на котором персонаж может начать делать задание

По нажатию клавиши "E"("У") в ITaskCompleter будет происходится поиск объектов в заданном радиусе с Layer Task
Если таких нет, то ничего не происходит, если есть, то происходит GetComponent<ITask>().open();
